cmake_minimum_required(VERSION 3.16)
add_library(la_util INTERFACE)
target_include_directories(la_util INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
set_target_properties(la_util PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED True)

if( CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR )
    enable_testing()
    project(la_util VERSION 0.2.0 LANGUAGES CXX)
    set(ADR_SAN -fsanitize=address -fno-omit-frame-pointer -g)
    set(UB_SAN -fsanitize=undefined -fno-omit-frame-pointer -g)
    set(THR_SAN -fsanitize=thread -fPIE -pie -fno-omit-frame-pointer -g)
    set(MEM_SAN -fsanitize=memory -fPIE -pie -fno-omit-frame-pointer -g -O2)

    set(CMAKE_CXX_STANDARD 20)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)

    include_directories( ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_CURRENT_SOURCE_DIR}/tests)

    add_executable(pool tests/test_pool.cpp)
    add_test(pool pool)
    add_executable(queue tests/test_queue.cpp)
    add_test(queue queue)

    add_executable(new_pool tests/test_new_pool.cpp)
    target_link_libraries(new_pool la_util atomic)
    # target_compile_options(new_pool PUBLIC  ${UB_SAN})
    # target_link_options(new_pool PUBLIC  -fsanitize=undefined )
    target_compile_options(new_pool PUBLIC  ${THR_SAN})
    target_link_options(new_pool PUBLIC  -fsanitize=thread )
    # target_compile_options(new_pool PUBLIC  ${ADR_SAN})
    # target_link_options(new_pool PUBLIC  -fsanitize=address )
    # target_compile_options(new_pool PUBLIC  ${MEM_SAN})
    # target_link_options(new_pool PUBLIC  -fsanitize=memory )
    set_target_properties(new_pool PROPERTIES CXX_STANDARD 20 CXX_STANDARD_REQUIRED True)
endif()
